### ISSUE TITLE
no search bar in full screen mode

### ISSUE THREAD

**Issue by nIghTcoderr** [ATechnocratis/widefox#1]
![изображение](https://user-images.githubusercontent.com/97761173/151498486-ac66a6b2-52a8-4d64-bdfd-f438c5a6556c.png)
I made all steps right as i think, but It doesnt work correctly :/
Sorry if ive made sth wrong xd

last pic is in windows mode
![изображение](https://user-images.githubusercontent.com/97761173/151499026-ef9e19de-bfb0-48b2-a964-a29126704f73.png)

**Comment by ATechnocratis** [comment]
Hello, so first check if scripts are working, for example is Tree Style Tab sidebar auto-hidden when switching to normal window mode from maximized?

**Edit**: Looking at your scrollbar the floating scroll bar script is not working, so scripts  not working is probably your issue. Check  [Enable script support  instructions again](https://github.com/ATechnocratis/widefox#4-enable-script-support)  also try cleaning startup cache again from about:support .

**Comment by ATechnocratis** [comment]
Also your normal window seems broken too , [click and follow step 6 instructions](https://github.com/ATechnocratis/widefox#6-customize--toolbar.)

In addition  I see that you use the show pinned tabs as favicon in TST, which Widefox didn't support, so I updated the style to support it now. 

Update the `./userContent-files/treestyletab.css`  with the new one.

**Comment by nIghTcoderr** [comment]
So i made 6 step again and renewed treestyletab.css file (upd: thx for that, its really comfortable to use):
![изображение](https://user-images.githubusercontent.com/97761173/151652397-edd9661d-5baa-49db-9e0f-d0d8645e9175.png)
![изображение](https://user-images.githubusercontent.com/97761173/151652415-df2f973e-decf-4ec1-b68b-bfdfb06d2326.png)
![изображение](https://user-images.githubusercontent.com/97761173/151652426-356a1d94-704b-4ae7-9da0-5e389f91ad3b.png)



> **_"Enable script support instructions again"_**

I dont clearly understand this step
Should I make this instruction? And am I interested in both  scripts and extensions? xD
![изображение](https://user-images.githubusercontent.com/97761173/151651110-8cf46fde-9260-4ce0-8221-c6cd2a6e2532.png)

**Comment by ATechnocratis** [comment]
Yes follow these instructions, for utils download I'm only interested in scripts.

You can also  skip 4 and 5 from the list above.

**Comment by nIghTcoderr** [comment]
I made this instructions but nothing happened(

**Comment by ATechnocratis** [comment]
Are you on latest firefox version? Can you post your OS info? Script support might be blocked from an antivirus, if you can, download a portable version of firefox and try there to see if the problem persists.

Make sure you extract the step 1 zip inside your **installation** folder not your profile folder, also the utils folder inside your chrome folder in your firefox profile folder.

**Comment by ATechnocratis** [comment]
Also if you have multiple firefox versions installed make you sure you copy contents from the step 1 zip to the correct installation folder.

For example if you have firefox dev version and release version both installed. There is a different folder for each installation and you need to the one you use.

**Comment by nIghTcoderr** [comment]
So, I tried all, but didnt found the issue
thx you for trying to help(

**Comment by ATechnocratis** [comment]
I am sorry to hear this, most likely not your fault but a compatibility issue with the script loader. You can try creating an issue there, also if you are on an older version  of firefox you can try downloading an older version of the script loader.

**Comment by nIghTcoderr** [comment]
thx u for such an interesting firefox customization)
